/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import pessoas.Pessoa;

/**
 *
 * @author bruno
 */
public class AdicionarPessoa extends javax.swing.JPanel {

    /**
     * Creates new form AdicionarPessoa
     */
    public AdicionarPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDataNasc = new javax.swing.JLabel();
        textProfissao = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        labelProfissao = new javax.swing.JLabel();
        comboTipoSangue = new javax.swing.JComboBox<>();
        textDataNasc = new javax.swing.JFormattedTextField();
        labelCpf = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelTipoSangue = new javax.swing.JLabel();
        textCpf = new javax.swing.JFormattedTextField();
        labelSexo = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox<>();
        botaoInserir = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));
        setLayout(null);

        labelDataNasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDataNasc.setText("Data Nasc:");
        add(labelDataNasc);
        labelDataNasc.setBounds(10, 130, 80, 30);
        add(textProfissao);
        textProfissao.setBounds(80, 170, 250, 30);

        labelID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelID.setText("ID:");
        add(labelID);
        labelID.setBounds(20, 20, 30, 20);

        textID.setEnabled(false);
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });
        add(textID);
        textID.setBounds(80, 20, 80, 20);

        labelProfissao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelProfissao.setText("Profissao:");
        add(labelProfissao);
        labelProfissao.setBounds(10, 170, 70, 30);

        comboTipoSangue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A+", "A-", "AB+", "AB-", "O+", "O-" }));
        comboTipoSangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoSangueActionPerformed(evt);
            }
        });
        add(comboTipoSangue);
        comboTipoSangue.setBounds(80, 260, 80, 30);

        try {
            textDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textDataNasc.setText("  /     /");
        textDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataNascActionPerformed(evt);
            }
        });
        add(textDataNasc);
        textDataNasc.setBounds(80, 130, 140, 30);

        labelCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCpf.setText(" CPF:");
        add(labelCpf);
        labelCpf.setBounds(10, 220, 50, 20);

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNome.setText("Nome:");
        add(labelNome);
        labelNome.setBounds(10, 60, 50, 20);
        add(textNome);
        textNome.setBounds(80, 50, 380, 30);

        labelTipoSangue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTipoSangue.setText("Tipo Sangue:");
        add(labelTipoSangue);
        labelTipoSangue.setBounds(0, 260, 100, 30);

        try {
            textCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(textCpf);
        textCpf.setBounds(80, 210, 160, 30);

        labelSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSexo.setText(" Sexo:");
        add(labelSexo);
        labelSexo.setBounds(10, 100, 50, 17);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Feminino" }));
        comboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSexoActionPerformed(evt);
            }
        });
        add(comboSexo);
        comboSexo.setBounds(80, 90, 120, 30);

        botaoInserir.setBackground(new java.awt.Color(255, 255, 153));
        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });
        add(botaoInserir);
        botaoInserir.setBounds(50, 390, 90, 30);

        botaoLimpar.setBackground(new java.awt.Color(255, 255, 153));
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        add(botaoLimpar);
        botaoLimpar.setBounds(420, 390, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void textDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataNascActionPerformed

    private void comboTipoSangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoSangueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoSangueActionPerformed

    private void comboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSexoActionPerformed

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
       Pessoa p1 = new Pessoa();
       
       p1.setId(Janelas.getInstance().listPessoa.size());
       p1.setNome(textNome.getText());
       p1.setSexo(comboSexo.getSelectedItem().toString());
       
       SimpleDateFormat dataFormato = new SimpleDateFormat ("dd/MM/y");
       try{
          Date data = dataFormato.parse(textDataNasc.getText());
          p1.setDataNascimento(data); 
       }catch (ParseException ex){
          
           System.out.println("Data inserida esta incorreta");
       }
        p1.setProfissao(textProfissao.getText());
        p1.setCpf(textCpf.getText());
        p1.setTipoSanguineo(comboTipoSangue.getSelectedItem().toString());
        
        Janelas.getInstance().listPessoa.add(p1);
       // int i;
       // for (i =0; i<Janelas.getInstance().listPessoa.size(); i++){
        
          ///  System.out.println(Janelas.getInstance().listPessoa.get(i).getNome());
        //}
        JOptionPane.showMessageDialog(this,"o usuario de id  \t "+p1.getId()+" \t  foi inserido com sucesso");
    }//GEN-LAST:event_botaoInserirActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
      textNome.setText(" ");
      comboSexo.setSelectedItem(" , ");
      textCpf.setText("   ,   ,   , ");
      textProfissao.setText(" ");
      
      
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
               
        
             
    }//GEN-LAST:event_textIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInserir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JComboBox<String> comboTipoSangue;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataNasc;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelProfissao;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTipoSangue;
    private javax.swing.JFormattedTextField textCpf;
    private javax.swing.JFormattedTextField textDataNasc;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textProfissao;
    // End of variables declaration//GEN-END:variables
}
