/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bruno
 */
public class PesquisarPessoa extends javax.swing.JPanel {

    /**
     * Creates new form PesquisarPessoa
     */
    public PesquisarPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPesquisaNome = new javax.swing.JLabel();
        textPesquisaNome = new javax.swing.JTextField();
        botaoPesquisaNome = new javax.swing.JButton();
        labelPesquisaCpf = new javax.swing.JLabel();
        textPesquisaCpf = new javax.swing.JTextField();
        botaoPesquisaCpf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisaPessoas = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));
        setLayout(null);

        labelPesquisaNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPesquisaNome.setText("Pesquisar por nome:");
        add(labelPesquisaNome);
        labelPesquisaNome.setBounds(20, 10, 124, 26);

        textPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPesquisaNomeActionPerformed(evt);
            }
        });
        add(textPesquisaNome);
        textPesquisaNome.setBounds(20, 50, 270, 30);

        botaoPesquisaNome.setText("Pesquisar");
        botaoPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaNomeActionPerformed(evt);
            }
        });
        add(botaoPesquisaNome);
        botaoPesquisaNome.setBounds(300, 50, 90, 30);

        labelPesquisaCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPesquisaCpf.setText("Pesquisar por CPF:");
        add(labelPesquisaCpf);
        labelPesquisaCpf.setBounds(20, 90, 124, 26);
        add(textPesquisaCpf);
        textPesquisaCpf.setBounds(20, 120, 270, 30);

        botaoPesquisaCpf.setText("Pesquisar");
        add(botaoPesquisaCpf);
        botaoPesquisaCpf.setBounds(300, 120, 90, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaPesquisaPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sexo", "Data Nascimento", "Profissao", "CPF", "Tipo Sanguineo"
            }
        ));
        tabelaPesquisaPessoas.setToolTipText("");
        jScrollPane1.setViewportView(tabelaPesquisaPessoas);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 980, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaNomeActionPerformed

        int linhas, i, tamanho;

        DefaultTableModel modelo = (DefaultTableModel) tabelaPesquisaPessoas.getModel();
        linhas = tabelaPesquisaPessoas.getRowCount();

        if (linhas >= 1) {
                 modelo.setRowCount(0);

                }
            tamanho = Janelas.getInstance().listPessoa.size();

        for (i = 0; i < tamanho; i++) {

            if (Janelas.getInstance().listPessoa.get(i).getNome().equals(textPesquisaNome.getText())) {

                // REPARA NO NIVEL DESSA LINHA.
                Object[] linha = {
                    Janelas.getInstance().listPessoa.get(i).getId(),
                    Janelas.getInstance().listPessoa.get(i).getNome(),
                    Janelas.getInstance().listPessoa.get(i).getSexo(),
                    Janelas.getInstance().listPessoa.get(i).getDataNascimento(),
                    Janelas.getInstance().listPessoa.get(i).getProfissao(),
                    Janelas.getInstance().listPessoa.get(i).getCpf(),
                    Janelas.getInstance().listPessoa.get(i).getTipoSanguineo()
                };

                modelo.addRow(linha);
            }

        }

    }//GEN-LAST:event_botaoPesquisaNomeActionPerformed

    private void textPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPesquisaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPesquisaNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisaCpf;
    private javax.swing.JButton botaoPesquisaNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPesquisaCpf;
    private javax.swing.JLabel labelPesquisaNome;
    private javax.swing.JTable tabelaPesquisaPessoas;
    private javax.swing.JTextField textPesquisaCpf;
    private javax.swing.JTextField textPesquisaNome;
    // End of variables declaration//GEN-END:variables
}
